### PR TITLE
Don't use into with a non-empty list as this is deprecated in 1.8.0

### LINKED ISSUE #120: The Collectable protocol is deprecated for non-empty lists
I am getting this:

```
Enum.into/2 or "for" comprehensions with an :into option is incorrect when collecting into non-empty lists. If you're collecting into a non-empty keyword list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty list, consider concatenating the two lists with the ++ operator.
(elixir) lib/collectable.ex:83: Collectable.List.into/1
(phoenix_pubsub) lib/phoenix/tracker/state.ex:380: Phoenix.Tracker.State.merge_deltas/2
(phoenix_pubsub) lib/phoenix/tracker/delta_generation.ex:34: Phoenix.Tracker.DeltaGeneration.do_push/4
(phoenix_pubsub) lib/phoenix/tracker/shard.ex:519: Phoenix.Tracker.Shard.push_delta_generation/2
(phoenix_pubsub) lib/phoenix/tracker/shard.ex:169: Phoenix.Tracker.Shard.handle_info/2
```

With elixir 1.8 and phoenux_pubsub 1.1.1

### PR DESCRIPTION
**Pull request by Gazler**
See https://github.com/elixir-lang/elixir/commit/6023568bcfe48f74c8b1bca485f9f9c984ab0664

Closes #120

### CODE REVIEW

**Comment by quolpr** [comment]
Wow, so fast!

**Comment by arjan** [comment]
Any chance this gets merged soon? Warnings in the test output driving me nuts ;-)

**Comment by arjan** [comment]
@chrismccord could you take a look at this, it is a trivial fix.

**Comment by princemaple** [comment]
Sorry about pinging again @chrismccord , this is really taking over the debugging log. If someone could take a look and merge (and make a release :wink:) we'd be immensely thankful.

**Comment by arjan** [comment]
Maybe we could ping another maintainer... @josevalim ? :stuck_out_tongue_winking_eye:

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by denvaar** [comment]
Thank you for this update!

**Comment by princemaple** [comment]
Looks like Jose doesn't have the permission to push this one to hex... 😂

**Pull request merged**
