### PR TITLE
start adding child_spec to adapters

### PR DESCRIPTION
**Pull request by pragdave**
Chris:

This is just a pathfinder to see if you're happy. If  so, I'll do it for redis, too.

Dave

### CODE REVIEW

**Comment by chrismccord** [comment]
Thanks! Please go ahead with redis! ❤️❤️❤️❤️🐥🔥

**Comment by josevalim** [comment]
@pragdave @chrismccord what do you think about only passing keywords, this way we don't need to nest tuples?

    {Phoenix.PubSub.PG2, name: Foo, ...}

We just need to pop the name and raise if it doesn't exist.

Thoughts?

**Comment by pragdave** [comment]
I felt the API should look the same as start_link.

**Comment by josevalim** [comment]
@pragdave yeah, that's a good point.

Although @pragdave, I have to point out you would probably be the first person to tell me we should let go of the "past" and go with what we think looks best, regardless of how it was before. :) I am not saying the keyword approach is best, I am just saying we probably don't need to get attached to the previous API.

For the Registry in Elixir, we went with the `{Module, opts}` route and even added a `start_link/1` to mirror it. YMMV.

**Comment by chrismccord** [comment]
I'm fine with the keyword route as well, but I think we should add a /1 clause for start_link if we go that route since converting from the old style to the new child spec will be least surprising if the options match. My only hesitation is I went start_link/2 because `name` is always required so making it part of the keyword option lessens its significance a bit. Of course, Keyword.fetch! solves it so I think it would be fine.

**Comment by pragdave** [comment]
Lol.

One of my concerns is that there's no obvious place to look for the
documentation of how to start something using the new supervisors. So
copying start_link seemed reasonable as a convention.

Although I'm the first person to agree that a nested tuple looks ugly,
there's another side to the coin. Keyword lists are typically used for
options; they stop you having to have functions with 17 arguments when you
only want to specify two of them. But there name is not an option. It's
required. So there's a strong indication that it should be it's own
parameter.


On Jan 17, 2018 09:08, "José Valim" <notifications@github.com> wrote:

@pragdave <https://github.com/pragdave> yeah, that's a good point.

Although @pragdave <https://github.com/pragdave>, I have to point out you
would probably be the first person to tell me we should let go of the
"past" and go with what we think looks best, regardless of how it was
before. :) I am not saying the keyword approach is best, I am just saying
we probably don't need to get attached to the previous API.

For the Registry in Elixir, we went with the {Module, opts} route and even
added a start_link/1 to mirror it. YMMV.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/phoenixframework/phoenix_pubsub/pull/95#issuecomment-358333422>,
or mute the thread

**Comment by josevalim** [comment]
Keywords can also be used to give "names" to arguments, especially when it may be unclear what they are without the option. For example:

    {Phoenix.PubSub.PG2, MyApp.Foo}

vs:

    {Phoenix.PubSub.PG2, name: MyApp.Foo}

**Comment by pragdave** [comment]
True. But then we'd have


{ child: Phoenix.PubSub.PG2, name: :Fred }


At which point someone would ask why user a tuple?


I actually originally wrote the PR using a name: option, then changed it.


I'm happy to change it back. Someone make the call.



On Wed, Jan 17, 2018 at 9:33am, José Valim < notifications@github.com [notifications@github.com] > wrote:
Keywords can also be used to give "names" to arguments, especially when it may be unclear what they are without the option. For example:

{Phoenix.PubSub.PG2, MyApp.Foo}


vs:

{Phoenix.PubSub.PG2, name: MyApp.Foo}

**Comment by pragdave** [comment]
Is there a decision on this?

**Comment by josevalim** [comment]
@pragdave agreed. :)

I will gladly delegate the decision to @chrismccord. :D

**Comment by chrismccord** [comment]
Let's go with the keyword list and we'll make sure to raise if name isn't provided. I'll make the change here, meanwhile @pragdave can you send a PR based on this to phoenix_pubsub_redis? Thanks!

**Comment by pragdave** [comment]
so start_link becomes just options too?

**Comment by chrismccord** [comment]
yes, but for backwards compatibility we need to keep the 2-arity clause. Currently pubsub adapters are expected to be start_link/2

**Comment by pragdave** [comment]
Yup: I was going to do that for both adapters.

**Pull request merged**
